### ISSUE TITLE
How could I prepared the training data for  a model for estimate the wild video‘s prediction. 

### ISSUE THREAD

**Issue by hujb48** [edouardelasalles/srvp#13]
@White-Link Hi, It is a great work! And I am a new at this field, so maybe the question is a bit unprofessional: How could I prepared the training data for a model for estimate the wild video‘s prediction, for example , I would like to predict any video I want, what should I do? Thanks a lot, Hu.

**Comment by White-Link** [comment]
Hi, thank you for your interest in our work!

Indeed, this is a tough question that goes beyond the scope of our paper and code. There is, to our knowledge, no model that is able to perform satisfying predictions on complex real-life data without restriction, even at low resolution. You may be interested in papers performing experiments on related datasets such as Kinetics (see e.g. https://openreview.net/pdf?id=rJgsskrFwH).

For our model to work on such datasets, you would need to adapt its design and scale it to match the complexity of the data. As is, SRVP has the same encoder and decoder architecture as [SVG](https://sites.google.com/view/svglp/) for fair comparisons purposes, but integrating more powerful architectures should enhance its performance, as hinted [here](https://openaccess.thecvf.com/content_ICCV_2019/html/Castrejon_Improved_Conditional_VRNNs_for_Video_Prediction_ICCV_2019_paper.html) and [here](https://proceedings.neurips.cc/paper/2019/hash/f7177163c833dff4b38fc8d2872f1ec6-Abstract.html) on comparable variational methods.

Good luck with your research!
