### ISSUE TITLE
Training parameters to reproduce results

### ISSUE THREAD

**Issue by dbadrian** [edouardelasalles/srvp#2]
Dear authors,

firstly, thanks for providing the code to your interesting paper! Great stuff.

I was trying to start reproducing some of the results (aka figuring out how to use everything provided).
You provided most of the architectural choices/parameters in the paper, but I was wondering if I also figured it out correctly with using them here.

For example, from my understanding, to run the stochastic video prediction:
```
python train.py --dataset smmnist --data_dir $DATA_FOLDER --nc 1 --ny 20 --nz 20 --nt_cond 5 --seq_len 15 --nt_inf 5 --save_path $SAVE_FOLDER
```
I guess, you set nt_inf always to the same number of nt_cond, the number of conditioning frames?

Maybe you could provide some, if not all, lines to run the experiments in the README.md as well, as it makes it a lot easier to figure things out. 

Greatly appreciated!

PS: Is there a way to monitor the progress? For me it seems it just does the whole training without any in between validation testing/outputting temporary results? Is this intended or user error?
I thought 'chkpt_interval' might do something as cmd parameter, but it does not seem to trigger anything.

**Comment by edouardelasalles** [comment]
Hi,

Thank you for your interest in our work.

Your command for training on Moving MNIST is correct, you can add `--beta_z 2` to match our hyperparameters.

`nt_cond` and `nt_inf` are often set to the same values but are slightly different. `nt_cond` is the number of conditioning frames used while testing. On the other hand, `nt_inf` (denoted by `k` in the paper) is the number of frames used to infer the distribution of the initial condition `y_0` (denoted by `y_1` in the paper) and to compute the content variable `w`. So `nt_inf <= nt_cond`.

Thank you for your suggestion, we will add precise commands to run the experiments in the near future.

We also plan on integrating validations and checkpoints soon.

**Comment by dbadrian** [comment]
Dear Edouard,

thank you for getting back quickly. 

Yes, I missed the beta_z, thanks! 
Indeed, I understood the difference, but I think, for your experiments, it was always kept the same?

Thanks for the update soon, it will help people a lot! Thanks!

**Comment by White-Link** [comment]
Hi David,

We kept the same value for `nt_cond` and `nt_inf` for Moving MNIST and BAIR, but not for KTH and Human3.6M, for which `nt_inf` is set to 3, while `nt_cond` is 10 for KTH and 8 for Human3.6M.

**Comment by edouardelasalles** [comment]
Hi David,

We just pushed a new version of the code including model selection and checkpointing, as well as a more detailed README with more precise instructions.

We are now closing this issue but feel free to re-open it or contact us if you have any further question.

**Comment by dbadrian** [comment]
Great, looking good!
Thank you very much for the updated project files!
